name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "cmdline-tools;latest"
          yes | sdkmanager --licenses

      - name: Ensure android project exists (flutter create if missing)
        run: |
          if [ ! -d "android" ]; then
            flutter create .
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Build Release APK (unsigned)
        run: flutter build apk --release

      - name: Upload Release (unsigned) APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: build/app/outputs/flutter-apk/app-release.apk
