name: espetos_vendas
description: Controle de vendas de espetos com dashboard, PDF e CSV
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
